const MONTH_COL_IN_BS_SHEET: number = 1;
const CASH_COL_IN_BS_SHEET: number = MONTH_COL_IN_BS_SHEET + 1;
const NOTES_AND_ACCOUNTS_RECEIVABLE_TRADE_COL_IN_BS_SHEET: number =
  CASH_COL_IN_BS_SHEET + 1;
const OTHER_RECEIVABLES_COL_IN_BS_SHEET: number =
  NOTES_AND_ACCOUNTS_RECEIVABLE_TRADE_COL_IN_BS_SHEET + 1;
const DEPOSITS_PAID_COL_IN_BS_SHEET: number =
  OTHER_RECEIVABLES_COL_IN_BS_SHEET + 1;
const SHORT_TERM_LOANS_COL_IN_BS_SHEET: number =
  DEPOSITS_PAID_COL_IN_BS_SHEET + 1;
const ALLOWANCE_COL_IN_BS_SHEET: number =
  SHORT_TERM_LOANS_COL_IN_BS_SHEET + 1;
const CURRENT_ASSETS_COL_IN_BS_SHEET: number =
  ALLOWANCE_COL_IN_BS_SHEET + 1;
const NON_CURRENT_ASSETS_COL_IN_BS_SHEET: number =
  CURRENT_ASSETS_COL_IN_BS_SHEET + 1;
const CURRENT_LIABILITIES_COL_IN_BS_SHEET: number =
  NON_CURRENT_ASSETS_COL_IN_BS_SHEET + 1;
const NON_CURRENT_LIABILITIES_COL_IN_BS_SHEET: number =
  CURRENT_LIABILITIES_COL_IN_BS_SHEET + 1;
const RETAINED_EARNINGS_COL_IN_BS_SHEET: number =
  NON_CURRENT_LIABILITIES_COL_IN_BS_SHEET + 1;