const MONTH_COL_IN_CF_SHEET: number = 1;
const OPERATING_COL_IN_CF_SHEET: number = MONTH_COL_IN_CF_SHEET + 1;
const INVESTING_COL_IN_CF_SHEET: number = OPERATING_COL_IN_CF_SHEET + 1;
const FINANCING_COL_IN_CF_SHEET: number = INVESTING_COL_IN_CF_SHEET + 1;
const PROCEEDS_FROM_SHORT_TERM_BORROWINGS_COL_IN_CF_SHEET: number =
  FINANCING_COL_IN_CF_SHEET + 1;
const REPAYMENT_OF_SHORT_TERM_BORROWINGS_COL_IN_CF_SHEET: number =
  PROCEEDS_FROM_SHORT_TERM_BORROWINGS_COL_IN_CF_SHEET + 1;
const REPAYMENT_OF_LONG_TERM_BORROWINGS_COL_IN_CF_SHEET: number =
  REPAYMENT_OF_SHORT_TERM_BORROWINGS_COL_IN_CF_SHEET + 1;
