const MONTH_COL_IN_CF_SHEET: number = 1;
const OPERATING_COL_IN_CF_SHEET: number = MONTH_COL_IN_CF_SHEET + 1;
const INVESTING_COL_IN_CF_SHEET: number = OPERATING_COL_IN_CF_SHEET + 1;
const FINANCING_COL_IN_CF_SHEET: number = INVESTING_COL_IN_CF_SHEET + 1;
